services:
  sylius.listener.add_to_cart:
    class: FMDD\SyliusCartBlamerPlugin\Listener\AddToCartListener
    arguments:
      - "@router"
    tags:
      - {name: 'kernel.event_listener', event: 'sylius.order_item.pre_update', method: 'onSuccessfulAddToCart'}

  sylius.listener.cart_blamer:
    class: FMDD\SyliusCartBlamerPlugin\EventListener\CartBlamerListener
    arguments:
      - "@sylius.manager.order"
      - "@sylius.context.cart"
      - "@sylius.context.cart.session_and_channel_base"
    tags:
      - {name: 'kernel.event_listener', event: 'sylius.user.security.implicit_login', method: 'onImplicitLogin'}
      - {name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onInteractiveLogin'}
