services:
  sylius.listener.add_to_cart:
    class: FMDD\SyliusCartBlamerPlugin\Listener\AddToCartListener
    arguments:
      - "@router"
    tags:
      - {name: 'kernel.event_listener', event: 'sylius.order_item.pre_update', method: 'onSuccessfulAddToCart'}
